# Generated by Django 4.0.2 on 2022-02-28 09:50

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_cartdropuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdropuser',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with this email already exist'}, max_length=50, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='cartdropuser',
            name='username',
            field=models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exist'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
